tetherless-world/whyis

- default_vocab.ttl
- static/html/jsonLdEditor.html
- static/js/lib/jsonLdEditor.js
- static/js/whyis.js
- templates/edit_instance_view.html
- templates/new_instance_view.html
- Recursively adding constraints to new instance editor
- Recursively adding constraints to the context in json-ld
- Moved editor template to separate html file
> Latest features additions to the instance editor

- docs/views.md
- main.py
Updated documentation on the process
> Added ability to add custom Jinja filters from the application

- .circleci/config.yml
- .gitignore
- commands.py
- dockerfiles/Dockerfile
- dockerfiles/docker-compose-dev.yml
- dockerfiles/docker-entrypoint.sh
- requirements/dev.txt
Report test results to CircleCI via a JUnit .xml file.
@jimmccusker please review.
> Test reporting

- docker/README.md
- docker/compose/monolithic/docker-compose.yml
- docker/compose/split/app/docker-compose.yml
- docker/compose/split/db/docker-compose.yml
Mount /data on the host in all of the Docker container.
Should probably use persistent volumes instead, but this is the simpler solution for the time being.
> Mount docker volumes

- docker/image/load-whyis-data.sh
Output .err and .out files for app load-data.sh
> Load debugging

- whyis/commands/configure.py
- whyis/commands/create_user.py
- whyis/commands/list_routes.py
- whyis/commands/load_nanopub.py
- whyis/commands/run_interpreter.py
- whyis/commands/test.py
- whyis/commands/test_agent.py
- whyis/commands/uninstall_app.py
- whyis/commands/update_user.py
Added docstrings to CLI commands and their options
> Cli documentation

- main.py
- tests/api/test_nanopub_crud.py
- tests/api/test_tableview.py
- whyis/blueprint/tableview/__init__.py
- whyis/blueprint/tableview/delete_tableview.py
- whyis/blueprint/tableview/get_tableview.py
- whyis/blueprint/tableview/post_tableview.py
- whyis/blueprint/tableview/put_tableview.py
- whyis/blueprint/tableview/tableview_blueprint.py
Flask blueprints for tableview api +  testing
> Tableview flask

- tests/unit/whyis_test/autonomic/test_setlr_agents.py
- whyis/autonomic/autonomic_setlr.py
- whyis/test/agent_unit_test_case.py
fixed issue with output not being sent correctly to the graph.
> Added unit test for setlr

- whyis/commands/test.py
- Adds `--apponly` parameter to the `test` command for running app tests only
> adds --apponly param

- docker/compose/monolithic/docker-compose.dev.yml
Quick and easy docker-compose build for development and testing. Added docker-compose.dev.yml
Also mount and un-mount multiple volumes with ease and quick restart.
Run:
docker-compose -f docker-compose.dev.yml up (for dev)
docker-compose up (for production)
> Added a docker-compose dev

- whyis/filters.py
Set 'typeProperty' param only if no value was passed.
> Fix bug in facet_values filter

- static/js/whyis_vue/utilities/views.js
> Use NODE_URI instead of parsing uri from url

- requirements/common.txt
Note: need to test with updated dependencies.
> Removed unidecode dependencies from filedepot

- .circleci/config.yml
> tag docker images on new git tag

- static/js/whyis_vue/components/pages/vega/view/vega-viewer.vue
I was having difficulties extending our custom dialog component so I just used md-dialog, which is part of vue material.
> Add spec view modal to chart view

- default_vocab.ttl
- static/js/whyis_vue/components/accordion.vue
- static/js/whyis_vue/components/index.js
- static/js/whyis_vue/components/pages/index.js
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_01.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_02.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_03.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_04.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_05.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_06.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_07.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_08.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_09.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_10.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_11.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_12.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_13.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_14.yaml
- static/js/whyis_vue/components/pages/sparql-templates/conf/PQ_15.yaml
- static/js/whyis_vue/components/pages/sparql-templates/index.js
- static/js/whyis_vue/components/pages/sparql-templates/sparql-template-page.vue
- static/js/whyis_vue/components/yasqe.vue
- static/js/whyis_vue/mixins/view-mixin.js
- static/js/whyis_vue/utilities/debounce.js
- static/package.json
- static/webpack.config.js
- templates/sparql_templates.html
Note: this implementation uses hardcoded templates and is intended to demo the template functionality
The hardcoded templates will be removed in the current sprint and will be stored/loaded from the triplestore instead.
> Add sparql template page

- static/js/whyis.js
- templates/ontology_view.html
Switched ontology view to use the Vue base template so we that we don't need html5 mode. Most of the tests now pass, but there seems to be a redis issue
> Potential fix for the CI failures

- requirements/common.txt
including switch from isAttributeOf to hasAttribute.
> Upgrade sdd2rdf for latest fixes

- static/.gitignore
- static/js/whyis_vue/assets/css/main.scss
- static/js/whyis_vue/components/pages/sparql-templates/index.js
- static/package.json
- static/webpack.config.js
- templates/base_vue.html
- upgrades most dev dependencies for vue application with adjustments for breaking changes
- configures webpack build so that all build artifacts go to `static/dist`
> Js dev upgrades

- main.py
- templates/class_view.html
- whyis/filters.py
class_view and attributes are now using it to its fullest extent, so hopefully at least there are examples.
> not everything was using lang_filter, but adding that seems to help.
